include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  errors:
    # Turn critical issues into errors (fail the build)
    unused_local_variable: error
    unused_element: error
    unused_import: error
    dead_code: error
    
    # Keep style preferences as warnings (don't fail the build)
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    deprecated_member_use: warning
    
  # Note: strict type checking is disabled for now to avoid breaking builds
  # with pre-existing type issues. Enable gradually as codebase improves.
  # language:
  #   strict-casts: true
  #   strict-inference: true
  #   strict-raw-types: true

linter:
  rules:
    # Keep all flutter_lints rules enabled
    - always_declare_return_types
    - always_use_package_imports
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - use_key_in_widget_constructors
