-- Create client_branches table for managing client branch locations
create table if not exists public.client_branches (
  id bigint generated by default as identity not null,
  client_id bigint not null,
  branch_name text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone null,
  constraint client_branches_pkey primary key (id),
  constraint client_branches_client_id_fkey foreign key (client_id)
    references public.clients (id)
    on update cascade
    on delete cascade
);

-- Create indexes for efficient queries
create index if not exists idx_client_branches_client_id
  on public.client_branches (client_id);

create index if not exists idx_client_branches_deleted_at
  on public.client_branches (deleted_at)
  where deleted_at is null;

-- Add trigger for automatic updated_at timestamp
create trigger trg_client_branches_updated_at
  before update on public.client_branches
  for each row
  execute function public.set_updated_at();

-- Add comment for documentation
comment on table public.client_branches is 'Stores branch locations for clients. Supports soft delete via deleted_at.';

