-- Create branches table for Choice Lux Cars company branches
-- This table stores the physical locations where Choice Lux Cars operates
-- Separate from client_branches which are client-specific locations

create table if not exists public.branches (
  id bigint generated by default as identity not null,
  name text not null,
  code text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint branches_pkey primary key (id),
  constraint branches_code_unique unique (code),
  constraint branches_name_unique unique (name)
) tablespace pg_default;

-- Create indexes for efficient lookups
create index if not exists idx_branches_code on public.branches using btree (code);
create index if not exists idx_branches_name on public.branches using btree (name);

-- Add trigger for automatic updated_at timestamp
drop trigger if exists trg_branches_updated_at on public.branches;
create trigger trg_branches_updated_at
  before update on public.branches
  for each row
  execute function public.set_updated_at();

-- Seed initial branch data
insert into public.branches (id, name, code) values
  (1, 'Durban', 'Dbn'),
  (2, 'Cape Town', 'Cpt'),
  (3, 'Johannesburg', 'Jhb')
on conflict (id) do nothing;

-- Set sequence to continue from 3 (in case manual inserts happen)
select setval('branches_id_seq', 3, true);

-- Add comment for documentation
comment on table public.branches is 'Stores Choice Lux Cars company branch locations. Used to allocate users, vehicles, and jobs to specific branches. NULL branch_id for users means Admin/National access.';

